# ISC License
#
# Copyright (c) 2026 Shane & Contributors
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
name: Release Manager

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write
  packages: write
  id-token: write

jobs:
  Update_On_Main:
    name: 🚀 Update Changelog & Prep Release
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📝 Release Drafter (Anticipate Version)
        id: drafter
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📤 Changelog Action
        uses: Bugs5382/changelog-updater-action@v0.3.2
        env:
          RELEASE_NOTES: >-
            ${{ steps.drafter.outputs.body }}
          RELEASE_VERSION: v${{ steps.drafter.outputs.resolved_version }}
        with:
          tag: ${{ env.RELEASE_VERSION }}
          notes: ${{ env.RELEASE_NOTES }}

      - name: 📤 Commit and Push Version Update
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(pre-release): v${{ steps.drafter.outputs.resolved_version }} [skip ci]"
